language: groovy
sudo: false
jdk:
- openjdk7
before_script:
- rm -rf target
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: RIKpTDF7YezEa4fY5hS976jYrYc0lnfSi0QN2WSF2GSkH+f66now8j7No3ARTdW3oYaimrGOywRO89BCE3npbK2Ea3Xen8/l/5jd+kMRVuIJiDxvYyyzQZ96hkbJ23CMNEXeX76Zz/pzZn3YDqqItz6txZwmOMoTBEY9tn3g0drGOAffaySVIR8MqeHhmC85bKSnfZlZ6kyhpzUrafXcgBBXPogzYSRo2DcPXL7UY6+AJul01y2x0Yu8GC4MPD13lmhgaloVLeuBfUzHbI5LhKtXt6kVVd75FFw7hariz39JXxT2X82Ljx01GULC1X4AlFH6A9IBmsprmPVmS2h/aZOL/Jd2eavjs2Tdqt9idvHyy3DwjLKnbNsDKj6r24ootdd0azffflgO2r5roEQ49Sb78HbrGEG9XYoB8WmjdYzuQ9KCpU6fVbfy2CG5WlJWUlR9nc46nVxlnrmFO3cng6LJOgRp7+KmHUw1g+6n0vfVnsFIau2vM8QBLeu/fwSAmTnYWiXosmPgfo/2DNDzEGV9Ir+QxHN8MnrXO5KYnzcR5MHKZapqqzoRYmsoyNdEQWeF/AKGySDXysZWrt/iR6iO2h3Niu9hyU5nQUg4Hq95oyEjZoWodogg3jmZaYlvu7UF5zpk5bFY6IcH/Pad7BKPUEmhO3WqT7MxbCVPmdE=
  - secure: RZSJS3IL8GdSKZy7HLvlpqdcN0qTJTvP2tGrYNBDp6OrA55eeJMV5OS0mp8OkhGj9rjSNM7UNE4FWqUzdRwmdXoKD/1ibKgUGQSLDWQZDjYA36QoxyjguVSQNys0AvHX7j/GJPH8I3o8YDr77IU2iGjQX3i4VAwDape0D+Q46Jl8TX58HcFkEo5QYl+EifBkzBgcHYfIblxQDNOEVKqp0GrfuED3zekAq2OzJfyxQZNunfOaDP/fiiz2uibumZzR8cVCEtQmRGZm+on5yNoFDWF5Gck0AvvBY7HAqzRZ62WJ3kHjNEg6h9ifwrRWrufA+uSj3Ppg4XXJbH5G88nQAZqNOk/UQ9MqWuQBtSglrur/NGEIpzdwkkJ0n4z2v5Q2yeQqDTAEEjmH4sIBpDlsYjas19EqTQcDfg2EUP9kb2LJ1v8w8GDiy0VyaiCvEm3lca4v7185kZxoT81XDB1JhQwC51OPKqD+1DqDk742glGCp4Jy9GJqrk4gxhjjExL24usQp0Ch9uEZ6AIKU550/UD8Isd6EH+PHA2Xla2WGHt2EnLz/DJPj0UuKIC6ScvBD5XxZvehrSePX+mBEjIe75BoMFJnKvDHiqJ1hrYHZi8gVdYn5hjuf5IZgJt6qan3pDKeYspWH0RFalRfkukTx6j/7dqW6piwvot2MQsbVkk=
